/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    'board-members': BoardMember;
    'stem-programs': StemProgram;
    media: Media;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    'stem-programs': StemProgramsSelect<false> | StemProgramsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      syncLumaEvents: TaskSyncLumaEvents;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'topo';
    variant?: ('tall' | 'short') | null;
    eyebrow?: string | null;
    /**
     * Main headline.
     */
    title?: string | null;
    /**
     * Optional. A phrase inside the title to render in the accent color (blue in light mode, gold in dark). Must match the title text exactly.
     */
    highlight?: string | null;
    subtitle?: string | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'events';
                  value: number | Event;
                } | null);
            /**
             * Full URL, a path like /events, a mailto: address, or an #anchor.
             */
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('primary' | 'secondary' | 'solidDark' | 'link') | null;
          };
          id?: string | null;
        }[]
      | null;
    showLocationPulse?: boolean | null;
  };
  layout: (
    | MissionPillarsBlock
    | FeaturedEventBlock
    | EventsGridBlock
    | StemImpactBlock
    | StemProgramsBlock
    | EligibilityBlock
    | PromoBandBlock
    | CtaBandBlock
    | ProposeProgramBlock
    | ContactBandBlock
    | LeadershipBoardBlock
    | ZeffyEmbedBlock
    | ContentBlock
    | MediaBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  startAt: string;
  endAt?: string | null;
  timezone?: string | null;
  /**
   * Optional human override, e.g. "February 2–5, 2026" or "Date TBA". Leave blank to format from the start date.
   */
  dateDisplay?: string | null;
  /**
   * Short venue line, e.g. "The Broadmoor, Colorado Springs, CO".
   */
  location?: string | null;
  /**
   * Full street address (optional).
   */
  address?: string | null;
  /**
   * RSVP link. Luma event page or any registration URL.
   */
  lumaUrl?: string | null;
  /**
   * Uploaded image. Takes priority over the Luma cover URL.
   */
  coverImage?: (number | null) | Media;
  /**
   * Cover image URL pulled from Luma.
   */
  coverUrl?: string | null;
  /**
   * Long description shown on the event page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Show as the big card on the home and events pages.
   */
  featured?: boolean | null;
  /**
   * Keep in the CMS but hide from the website.
   */
  hidden?: boolean | null;
  tag?: ('Flagship' | 'STEM' | 'Networking' | 'Symposium' | 'Social' | 'Emerging Leaders' | 'Awards') | null;
  /**
   * One or two sentences for cards. Luma does not provide this, so write it here.
   */
  blurb?: string | null;
  /**
   * Short bullet points shown beside a featured event (e.g. "Four days of strategic dialogue").
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  zeffy?: {
    enabled?: boolean | null;
    /**
     * Zeffy ticketing or donation form URL.
     */
    url?: string | null;
    buttonLabel?: string | null;
    embed?: boolean | null;
    height?: number | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  source?: ('manual' | 'luma') | null;
  /**
   * Luma event api_id (evt-…).
   */
  lumaEventId?: string | null;
  syncedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionPillarsBlock".
 */
export interface MissionPillarsBlock {
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  pillars?:
    | {
        icon?:
          | (
              | 'shield'
              | 'landmark'
              | 'briefcase'
              | 'graduationCap'
              | 'calendar'
              | 'sparkles'
              | 'mapPin'
              | 'mail'
              | 'users'
              | 'rocket'
            )
          | null;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'missionPillars';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedEventBlock".
 */
export interface FeaturedEventBlock {
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading?: string | null;
  mode?: ('auto' | 'manual') | null;
  event?: (number | null) | Event;
  viewAllLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredEvent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsGridBlock".
 */
export interface EventsGridBlock {
  showFeatured?: boolean | null;
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  scope?: ('upcoming' | 'upcomingThenPast' | 'past') | null;
  limit?: number | null;
  allEventsLabel?: string | null;
  emptyMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StemImpactBlock".
 */
export interface StemImpactBlock {
  eyebrow?: string | null;
  /**
   * Leave blank to use the STEM total from Site Settings. Rendered as "$500K+" style.
   */
  statOverride?: number | null;
  statCaption?: string | null;
  aside?: string | null;
  /**
   * How many programs to show (ordered by the "order" field, featured first).
   */
  limit?: number | null;
  linkLabel?: string | null;
  /**
   * Page the "See all" link goes to (usually STEM Grant).
   */
  linkPage?: (number | null) | Page;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stemImpact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StemProgramsBlock".
 */
export interface StemProgramsBlock {
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  showImpactStat?: boolean | null;
  impactEyebrow?: string | null;
  impactCaption?: string | null;
  impactBody?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stemPrograms';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EligibilityBlock".
 */
export interface EligibilityBlock {
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eligibility';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBandBlock".
 */
export interface PromoBandBlock {
  eyebrow?: string | null;
  /**
   * Heading segments joined by an accent "·" separator, e.g. RMCS26 · The Broadmoor · February 2–5, 2026
   */
  headingParts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  body?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    /**
     * Full URL, a path like /events, a mailto: address, or an #anchor.
     */
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('primary' | 'secondary' | 'solidDark') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  /**
   * Small uppercase label above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Optional short paragraph under the heading.
   */
  intro?: string | null;
  style?: ('centered' | 'splitTopo' | 'card') | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          /**
           * Full URL, a path like /events, a mailto: address, or an #anchor.
           */
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('primary' | 'secondary' | 'solidDark' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProposeProgramBlock".
 */
export interface ProposeProgramBlock {
  /**
   * HTML id so links like #apply can scroll here.
   */
  anchor?: string | null;
  eyebrow?: string | null;
  heading: string;
  /**
   * The email below is linked automatically where it appears in this text.
   */
  body?: string | null;
  /**
   * Leave blank to use the STEM contact email from Site Settings.
   */
  email?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          /**
           * Full URL, a path like /events, a mailto: address, or an #anchor.
           */
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('primary' | 'secondary' | 'solidDark' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'proposeProgram';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBandBlock".
 */
export interface ContactBandBlock {
  addressLabel?: string | null;
  emailLabel?: string | null;
  /**
   * Leave blank to use the STEM contact email from Site Settings.
   */
  email?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBoardBlock".
 */
export interface LeadershipBoardBlock {
  /**
   * Sections to render, in order. Members come from the Board Members collection.
   */
  groups?:
    | {
        group: 'exec' | 'admin' | 'programs' | 'strategy';
        eyebrow?: string | null;
        title: string;
        layout?: ('grid' | 'feature') | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    /**
     * Leave blank to use the President's email from Board Members.
     */
    email?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadershipBoard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ZeffyEmbedBlock".
 */
export interface ZeffyEmbedBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Zeffy form URL, e.g. https://www.zeffy.com/embed/ticketing/… or https://www.zeffy.com/en-US/ticketing/…
   */
  url: string;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'zeffyEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          /**
           * Full URL, a path like /events, a mailto: address, or an #anchor.
           */
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('primary' | 'secondary' | 'solidDark' | 'link') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  /**
   * Nicknames in quotes are fine, e.g. Jason "Cueball" Simmons.
   */
  name: string;
  /**
   * Rank / credentials, e.g. Lt Col, USAF (ret.)
   */
  postNominals?: string | null;
  role: string;
  group: 'exec' | 'admin' | 'programs' | 'strategy';
  /**
   * Portrait, ideally 4:5. Falls back to initials when empty.
   */
  photo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  /**
   * Full LinkedIn profile URL.
   */
  linkedin?: string | null;
  /**
   * GitHub profile URL or username.
   */
  github?: string | null;
  /**
   * Personal or company website URL.
   */
  website?: string | null;
  bio?: string | null;
  /**
   * Lower numbers appear first within a group.
   */
  order?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stem-programs".
 */
export interface StemProgram {
  id: number;
  name: string;
  /**
   * Partner organization, e.g. "University of Colorado Colorado Springs (UCCS)".
   */
  partner: string;
  /**
   * Short label for compact cards, e.g. "UCCS". Defaults to the partner name before any comma or parenthesis.
   */
  partnerShort?: string | null;
  description: string;
  /**
   * Optional partner / program URL.
   */
  link?: string | null;
  /**
   * Featured programs are shown first on the home page.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'syncLumaEvents' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'syncLumaEvents' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'stem-programs';
        value: number | StemProgram;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        variant?: T;
        eyebrow?: T;
        title?: T;
        highlight?: T;
        subtitle?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        showLocationPulse?: T;
      };
  layout?:
    | T
    | {
        missionPillars?: T | MissionPillarsBlockSelect<T>;
        featuredEvent?: T | FeaturedEventBlockSelect<T>;
        eventsGrid?: T | EventsGridBlockSelect<T>;
        stemImpact?: T | StemImpactBlockSelect<T>;
        stemPrograms?: T | StemProgramsBlockSelect<T>;
        eligibility?: T | EligibilityBlockSelect<T>;
        promoBand?: T | PromoBandBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        proposeProgram?: T | ProposeProgramBlockSelect<T>;
        contactBand?: T | ContactBandBlockSelect<T>;
        leadershipBoard?: T | LeadershipBoardBlockSelect<T>;
        zeffyEmbed?: T | ZeffyEmbedBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionPillarsBlock_select".
 */
export interface MissionPillarsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedEventBlock_select".
 */
export interface FeaturedEventBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  mode?: T;
  event?: T;
  viewAllLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsGridBlock_select".
 */
export interface EventsGridBlockSelect<T extends boolean = true> {
  showFeatured?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  scope?: T;
  limit?: T;
  allEventsLabel?: T;
  emptyMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StemImpactBlock_select".
 */
export interface StemImpactBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  statOverride?: T;
  statCaption?: T;
  aside?: T;
  limit?: T;
  linkLabel?: T;
  linkPage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StemProgramsBlock_select".
 */
export interface StemProgramsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  showImpactStat?: T;
  impactEyebrow?: T;
  impactCaption?: T;
  impactBody?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EligibilityBlock_select".
 */
export interface EligibilityBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBandBlock_select".
 */
export interface PromoBandBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  headingParts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  style?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProposeProgramBlock_select".
 */
export interface ProposeProgramBlockSelect<T extends boolean = true> {
  anchor?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  email?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBandBlock_select".
 */
export interface ContactBandBlockSelect<T extends boolean = true> {
  addressLabel?: T;
  emailLabel?: T;
  email?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadershipBoardBlock_select".
 */
export interface LeadershipBoardBlockSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        group?: T;
        eyebrow?: T;
        title?: T;
        layout?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        buttonLabel?: T;
        email?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ZeffyEmbedBlock_select".
 */
export interface ZeffyEmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  url?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startAt?: T;
  endAt?: T;
  timezone?: T;
  dateDisplay?: T;
  location?: T;
  address?: T;
  lumaUrl?: T;
  coverImage?: T;
  coverUrl?: T;
  description?: T;
  featured?: T;
  hidden?: T;
  tag?: T;
  blurb?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  zeffy?:
    | T
    | {
        enabled?: T;
        url?: T;
        buttonLabel?: T;
        embed?: T;
        height?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  source?: T;
  lumaEventId?: T;
  syncedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  postNominals?: T;
  role?: T;
  group?: T;
  photo?: T;
  email?: T;
  phone?: T;
  linkedin?: T;
  github?: T;
  website?: T;
  bio?: T;
  order?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stem-programs_select".
 */
export interface StemProgramsSelect<T extends boolean = true> {
  name?: T;
  partner?: T;
  partnerShort?: T;
  description?: T;
  link?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          /**
           * Full URL, a path like /events, a mailto: address, or an #anchor.
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    enabled?: boolean | null;
    link?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'events';
            value: number | Event;
          } | null);
      /**
       * Full URL, a path like /events, a mailto: address, or an #anchor.
       */
      url?: string | null;
      label: string;
    };
  };
  showThemeToggle?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short paragraph under the chapter name.
   */
  tagline?: string | null;
  affiliation?: {
    prefix?: string | null;
    label?: string | null;
    url?: string | null;
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'events';
                      value: number | Event;
                    } | null);
                /**
                 * Full URL, a path like /events, a mailto: address, or an #anchor.
                 */
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bottomNote?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          /**
           * Full URL, a path like /events, a mailto: address, or an #anchor.
           */
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Wordmark in the header.
   */
  shortName?: string | null;
  /**
   * Wordmark on small phones.
   */
  tinyName?: string | null;
  /**
   * Default meta description and Open Graph description.
   */
  description?: string | null;
  /**
   * Default social share image (1200×630).
   */
  ogImage?: (number | null) | Media;
  address?: {
    line1?: string | null;
    line2?: string | null;
  };
  /**
   * General chapter inquiries. Leave blank to use the President's email from Board Members.
   */
  contactEmail?: string | null;
  /**
   * STEM grant proposals (VP, Education).
   */
  stemEmail?: string | null;
  /**
   * Shown next to the pulsing dot in the home hero.
   */
  regionLine?: string | null;
  timezoneLabel?: string | null;
  /**
   * AFCEA International membership page.
   */
  membershipUrl?: string | null;
  luma?: {
    /**
     * Public calendar page.
     */
    calendarUrl?: string | null;
    /**
     * Luma calendar id (cal-…). Used by the event sync.
     */
    calendarApiId?: string | null;
    syncEnabled?: boolean | null;
    includePast?: boolean | null;
    lastSyncedAt?: string | null;
    lastSyncSummary?: string | null;
  };
  zeffy?: {
    /**
     * Optional general donation form URL.
     */
    donateUrl?: string | null;
  };
  /**
   * Total invested, used for the "$500K+" stat.
   */
  stemTotal?: number | null;
  stemTotalYear?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  showThemeToggle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  affiliation?:
    | T
    | {
        prefix?: T;
        label?: T;
        url?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  bottomNote?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  shortName?: T;
  tinyName?: T;
  description?: T;
  ogImage?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
      };
  contactEmail?: T;
  stemEmail?: T;
  regionLine?: T;
  timezoneLabel?: T;
  membershipUrl?: T;
  luma?:
    | T
    | {
        calendarUrl?: T;
        calendarApiId?: T;
        syncEnabled?: T;
        includePast?: T;
        lastSyncedAt?: T;
        lastSyncSummary?: T;
      };
  zeffy?:
    | T
    | {
        donateUrl?: T;
      };
  stemTotal?: T;
  stemTotalYear?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncLumaEvents".
 */
export interface TaskSyncLumaEvents {
  input: {
    includePast?: boolean | null;
  };
  output: {
    created?: number | null;
    updated?: number | null;
    skipped?: number | null;
    unpublishedMissing?: number | null;
    errors?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}